use 5.012;
use warnings;

use Perl::Dist::Strawberry;
use Perl::Dist::Strawberry::Step::OutputMSM_MSI;
use Perl::Dist::Strawberry::Step::CreateReleaseNotes;

my $b = Perl::Dist::Strawberry->new(
#********************************************************************************************
  app_fullname        => "Strawberry Perl",
  app_simplename      => "strawberry-perl",
  app_version         => "5.16.0.1",
  argv                => [
                           "-job",
                           "share\\32bit-5.16.0.0.pp",
                           "-restorepoints",
                           "-cpan_url",
                           "file://z:/strawberry_build/_cpan-mirror/",
                         ],
  beta                => 2,
  bits                => 32,
  build_dir           => "C:\\strawberry_build\\build",
  build_ENV           => {
                           APPDATA           => "C:\\strawberry_build\\env\\AppDataRoaming",
                           COMPUTERNAME      => "buildmachine",
                           HOMEDRIVE         => "C:",
                           HOMEPATH          => "\\strawberry_build\\env\\home\\",
                           INCLUDE           => undef,
                           LIB               => undef,
                           LOCALAPPDATA      => "C:\\strawberry_build\\env\\AppDataLocal",
                           PATH              => "C:\\strawberry\\perl\\site\\bin;C:\\strawberry\\perl\\bin;C:\\strawberry\\c\\bin;C:\\Windows\\system32;C:\\Windows",
                           PERL5DB           => undef,
                           PERL5LIB          => undef,
                           PERL5OPT          => undef,
                           PERL5SHELL        => undef,
                           PERL_JSON_BACKEND => undef,
                           PERL_MB_OPT       => undef,
                           PERL_MM_OPT       => undef,
                           PERL_YAML_BACKEND => undef,
                           PERLLIB           => undef,
                           TEMP              => "C:\\strawberry_build\\env\\temp",
                           TERM              => "dumb",
                           TMP               => "C:\\strawberry_build\\env\\temp",
                           USERNAME          => "builduser",
                           USERPROFILE       => "C:\\strawberry_build\\env\\UserProfile",
                         },
  cpan_url            => "file://z:/strawberry_build/_cpan-mirror/",
  debug_dir           => "C:\\strawberry_build\\debug",
  dist_sharedir       => "Z:\\strawberry_build\\SVN_Perl-Dist-Strawberry\\blib\\lib\\auto\\share\\dist\\Perl-Dist-Strawberry",
  download_dir        => "C:\\strawberry_build\\download",
  env_dir             => "C:\\strawberry_build\\env",
  image_dir           => "C:\\strawberry",
  image_dir_quotemeta => "c:\\\\strawberry",
  image_dir_url       => "file:///c:/strawberry",
  interactive         => 1,
  job                 => "share\\32bit-5.16.0.0.pp",
  offline             => 0,
  output              => {
                           distributions => [
                             "Compress-Raw-Zlib-2.053_fixed_rt77030",
                             "App-Cpan-1.5902",
                             "Archive-Extract-0.60",
                             "Archive-Tar-1.84",
                             "autodie-2.11",
                             "Compress-Raw-Bzip2-2.052",
                             "CPAN-Meta-2.120921",
                             "CPAN-Meta-Requirements-2.122",
                             "CPAN-Meta-YAML-0.008",
                             "CPANPLUS-0.9128",
                             "File-Fetch-0.34",
                             "Filter-1.43",
                             "HTTP-Tiny-0.018",
                             "IO-Compress-2.052",
                             "IPC-Cmd-0.78",
                             "Memoize-1.03",
                             "Module-Build-0.40",
                             "Module-Load-Conditional-0.50",
                             "Object-Accessor-0.44",
                             "Params-Check-0.36",
                             "Parse-CPAN-Meta-1.4404",
                             "PerlIO-via-QuotedPrint-0.07",
                             "Safe-2.33",
                             "Scalar-List-Utils-1.25",
                             "Search-Dict-1.07",
                             "Socket-2.001",
                             "Term-ANSIColor-3.02",
                             "App-Cpan-1.5902",
                             "Archive-Extract-0.60",
                             "Archive-Tar-1.84",
                             "autodie-2.11",
                             "Compress-Raw-Bzip2-2.052",
                             "CPAN-Meta-2.120921",
                             "CPAN-Meta-Requirements-2.122",
                             "CPAN-Meta-YAML-0.008",
                             "CPANPLUS-0.9128",
                             "File-Fetch-0.34",
                             "Filter-1.43",
                             "HTTP-Tiny-0.018",
                             "IO-Compress-2.052",
                             "IPC-Cmd-0.78",
                             "Memoize-1.03",
                             "Module-Build-0.40",
                             "Module-Load-Conditional-0.50",
                             "Object-Accessor-0.44",
                             "Params-Check-0.36",
                             "Parse-CPAN-Meta-1.4404",
                             "PerlIO-via-QuotedPrint-0.07",
                             "Safe-2.33",
                             "Scalar-List-Utils-1.25",
                             "Search-Dict-1.07",
                             "Socket-2.001",
                             "Term-ANSIColor-3.02",
                             "Algorithm-Diff-1.1902",
                             "Alien-Tidyp-v1.4.7",
                             "App-local-lib-Win32Helper-0.990",
                             "App-module-version-1.004",
                             "Archive-Zip-1.30",
                             "BerkeleyDB-0.51",
                             "Capture-Tiny-0.18",
                             "Class-ErrorHandler-0.01",
                             "Class-Inspector-1.27",
                             "Class-Loader-2.03",
                             "common-sense-3.5",
                             "Compress-Bzip2-2.09",
                             "Compress-Raw-Lzma-2.052",
                             "Compress-unLZMA-0.04",
                             "Convert-ASCII-Armour-1.4",
                             "Convert-ASN1-0.23",
                             "Convert-PEM-0.08",
                             "CPAN-Checksums-2.08",
                             "CPAN-DistnameInfo-0.12",
                             "CPAN-Inject-1.13",
                             "CPAN-SQLite-0.202",
                             "Crypt-Blowfish-2.12_patched",
                             "Crypt-CAST5_PP-1.04",
                             "Crypt-CBC-2.30",
                             "Crypt-DES-2.05",
                             "Crypt-DES_EDE3-0.01",
                             "Crypt-DH-0.06",
                             "Crypt-DSA-1.17",
                             "Crypt-IDEA-1.08_patched",
                             "Crypt-OpenPGP-1.06",
                             "Crypt-Primes-0.50",
                             "Crypt-Random-1.25",
                             "Crypt-Rijndael-1.09",
                             "Crypt-RIPEMD160-0.05",
                             "Crypt-RSA-1.99",
                             "Crypt-SSLeay-0.58",
                             "Crypt-Twofish-2.14",
                             "Data-Buffer-0.04",
                             "Data-Compare-1.22",
                             "Data-Random-0.06",
                             "DB_File-1.826",
                             "DBD-ADO-2.99",
                             "DBD-mysql-4.020_patched_h",
                             "DBD-ODBC-1.37",
                             "DBD-Pg-2.19.2",
                             "DBD-SQLite-1.35",
                             "DBI-1.620",
                             "DBIx-Simple-1.35",
                             "DBM-Deep-2.0006",
                             "Digest-BubbleBabble-0.02",
                             "Digest-HMAC-1.03",
                             "Digest-MD2-2.03",
                             "Digest-SHA1-2.13",
                             "Encode-Locale-1.03",
                             "FCGI-0.74",
                             "File-chmod-0.32",
                             "File-Copy-Recursive-0.38",
                             "File-Find-Rule-0.33",
                             "File-HomeDir-0.99",
                             "File-Listing-6.04",
                             "File-pushd-1.002",
                             "File-Remove-1.52",
                             "File-ShareDir-1.03",
                             "File-Slurp-9999.19",
                             "File-Which-1.09",
                             "GD-2.46_patched",
                             "HTML-Parser-3.69",
                             "HTML-Tagset-3.20",
                             "HTTP-Cookies-6.01",
                             "HTTP-Daemon-6.01",
                             "HTTP-Date-6.02",
                             "HTTP-Message-6.03",
                             "HTTP-Negotiate-6.01",
                             "Imager-0.90",
                             "IO-Compress-Lzma-2.052",
                             "IO-Interactive-0.0.6",
                             "IO-Socket-SSL-1.66",
                             "IO-String-1.08",
                             "IO-stringy-2.110",
                             "IPC-Run-0.91",
                             "IPC-Run3-0.045",
                             "IPC-System-Simple-1.21",
                             "JSON-2.53",
                             "JSON-XS-2.32",
                             "libwww-perl-6.04",
                             "local-lib-1.008004",
                             "LWP-MediaTypes-6.02",
                             "LWP-Online-1.08",
                             "LWP-Protocol-https-6.03",
                             "Math-BigInt-GMP-1.37",
                             "Math-GMP-2.06",
                             "Math-MPC-0.93",
                             "Math-MPFR-3.12",
                             "Math-Pari-2.01080605",
                             "Module-Signature-0.68",
                             "Mozilla-CA-20120309",
                             "Net-HTTP-6.03",
                             "Net-SMTP-TLS-0.12",
                             "Net-SSH2-0.44",
                             "Net-SSLeay-1.48",
                             "Number-Compare-0.03",
                             "PAR-1.005",
                             "PAR-Dist-0.48",
                             "PAR-Dist-FromPPD-0.03",
                             "PAR-Dist-InstallPPD-0.02",
                             "PAR-Repository-Client-0.25",
                             "PAR-Repository-Query-0.14",
                             "Params-Util-1.07",
                             "Parse-Binary-0.11",
                             "pip-1.19",
                             "pler-1.06",
                             "PPM-0.01_03",
                             "Probe-Perl-0.01",
                             "SOAP-Lite-0.714",
                             "Sort-Versions-1.5",
                             "String-CRC32-1.4",
                             "Sub-Uplevel-0.24",
                             "Task-Weaken-1.04",
                             "Term-ReadLine-Perl-1.0303",
                             "TermReadKey-2.30.02",
                             "Test-Deep-0.109",
                             "Test-Exception-0.31",
                             "Test-Manifest-1.23",
                             "Test-NoWarnings-1.04",
                             "Test-Script-1.07",
                             "Test-Tester-0.108",
                             "Test-Warn-0.24",
                             "Text-Diff-1.41",
                             "Text-Glob-0.09",
                             "Tie-EncryptedHash-1.24",
                             "Tree-DAG_Node-1.06",
                             "URI-1.60",
                             "Win32-API-0.68",
                             "Win32-EventLog-0.076",
                             "Win32-Exe-0.17",
                             "Win32-File-0.06",
                             "Win32-File-Object-0.02",
                             "Win32-OLE-0.1709",
                             "Win32-Process-0.14",
                             "Win32-TieRegistry-0.26",
                             "Win32-UTCFileTime-1.55",
                             "Win32-WinError-0.03",
                             "Win32API-Registry-0.32",
                             "WWW-RobotRules-6.02",
                             "XML-LibXML-1.97",
                             "XML-LibXSLT-1.77",
                             "XML-NamespaceSupport-1.11",
                             "XML-Parser-2.41",
                             "XML-SAX-0.99",
                             "XML-SAX-Base-1.08",
                             "XML-Simple-2.18",
                             "YAML-0.81",
                             "YAML-Tiny-1.51",
                             "CPAN-Mini-1.111008",
                             "Portable-1.15",
                           ],
                           msi => "C:\\strawberry_build\\output\\strawberry-perl-5.16.0.1-beta2-32bit.msi",
                           msi_guid => "78376C5E-6C02-1014-A370-F5F3AED71F0C",
                           msi_sha1 => 1,
                           msm => "C:\\strawberry_build\\output\\strawberry-perl-5.16.0.1-beta2-32bit.msm",
                           msm_guid => "78376C98-6C02-1014-A370-F5F3AED71F0C",
                           msm_id => "78376C98_6C02_1014_A370_F5F3AED71F0C",
                           msm_sha1 => 1,
                           perl_version => "5.15.9",
                           zip => "C:\\strawberry_build\\output\\strawberry-perl-5.16.0.1-beta2-32bit.zip",
                           zip_sha1 => 1,
                         },
  output_basename     => "strawberry-perl-5.16.0.1-beta2-32bit",
  output_dir          => "C:\\strawberry_build\\output",
  package_url         => "http://strawberryperl.com/package/",
  perl_debug          => 0,
  restore_dir         => "C:\\strawberry_build\\restore",
  restorepoints       => 1,
  target              => "msi+zip+portable",
  test_core           => 0,
  test_modules        => 1,
  verbosity           => 3,
  wixbin_dir          => undef,
  working_dir         => "C:\\strawberry_build",
#********************************************************************************************
);

my $m = Perl::Dist::Strawberry::Step::CreateReleaseNotes->new(
  boss=>$b,
  config=>{
#********************************************************************************************  
       XXXexclude  => 666,
#********************************************************************************************
    }
);

$m->run;